blog-project/app/home/__init__.py
from flask import Blueprint
home = Blueprint("home",__name__)
import app.home.views

blog-project/app/home/views.py
from . import home
from flask import render_template, url_for, request, session, jsonify
from app.models import *
from app.dysms import demo_sms_send
import os, json, time, random, re, random


# 请求处理之前的 装饰器
@home.before_request
def checklogin():
    # 获取当前的请求路径
    path = request.path
    # 要求登录才能请求的路径
    urllist = [url_for('home.createblog')]
    if path in urllist:
        # 判断是否登录
        if not session.get('VipUser',None):
            return '<script>alert("请先登录");location.href="'+url_for('home.login')+'?next='+path+'"</script>'


# 退出登录
@home.route('/logout/')
def logout():
    session.pop('VipUser')
    return "<script>alert('退出成功');location.href='/'</script>"


# 发送验证码
@home.route('/send_vcode', methods=['GET','POST'])
def sendSMS():
    # 接受手机号
    phone = request.values['phone']
    print(phone)
    # 生成验证码
    code = random.randint(10000, 99999)
    # 存储到session中
    # session['code'] = code
    print(code)

    res = demo_sms_send.send(code, phone)
    res = jsonify(eval(res))
    print(res)
    print(type(res))

    # 将验证码存入 session
    session['vcode'] = code

    print('session:',session['vcode'])
    # vcode = Vcode.query.first()
    # if vcode:
    #     vcode.vcode = code
    #     db.session.add(vcode)
    #     db.session.commit()
    # else:
    #     vcode = Vcode(vcode=code)
    #     db.session.add(vcode)
    #     db.session.commit()

    return res


# 注册
@home.route('/register',  methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        data = {
            'login':url_for('home.login'),
            'register':url_for('home.register'),
            'sendSMS':url_for('home.sendSMS')
        }

        return render_template('home/lw-re.html', url=data)
    elif request.method == 'POST':
        try:
            if str(request.values['vcode']) == str(session['vcode']):
            
                data = {}
                data['email'] = request.values['email']
                data['pwd'] = User.MD5password(request.values['pwd'])
                data['phone'] = request.values['phone']

                ob = User(**data)
                db.session.add(ob)
                db.session.commit()

                res = '<script>alert("注册成功,请登录!");location.href="{login}"</script>'.format(login=url_for('home.login'))
                return res
            else:
                res = '<script>alert("注册失败,验证码错误,请重新注册!!");history.back(-1)</script>'
                return res

        except:
            res = '<script>alert("注册失败,请重新注册!!");history.back(-1)</script>'
            return res


# 发布博文
@home.route('/createblog',methods=['GET','POST'])
def createblog():
    if request.method == 'GET':
        # 获取所有的标签
        tags = Tags.query.all()
        # 返回一个博文发布页面
        return render_template('/home/blogs/add.html', tags=tags)
    elif request.method == "POST":
        data = {}
        # 接受消息
        data['title'] = request.values['title']
        data['context'] = request.values['context']
        data['uid'] = session['VipUser']['id']
        print(data)

        # 入库 加标签
        ob = Posts(**data)
        ob.tags = list(map(lambda x:Tags.query.get(x),request.form.getlist('tags')))
        db.session.add(ob)
        db.session.commit()
        
        return '<script>alert("发布成功");location.href="{}"</script> '.format(url_for('home.bloginfo',pid=ob.id))


# 博文详情
# @home.route('/bloginfo/<int:pid>')
# def bloginfo(pid):
#     # 读取文章内容
#     info = Posts.query.get(pid)
#     tags = info.tags
#     # 查找评论信息
#     comments = Comments.query.filter_by(posts_id=pid).all()

#     data = {'info':info, 'tags': tags, 'comments':comments}

#     return render_template('home/blogs/article.html', info=data)

@home.route('/bloginfo/<int:pid>')
def bloginfo(pid):
    # 读取文章内容
    blog = Posts.query.get(pid)
    tags = blog.tags
    # 查找评论信息
    comments = Comments.query.filter_by(posts_id=pid).all()

    data = {'blog':blog, 'tags': tags, 'comments':comments}

    return render_template('home/blogs/article.html', **data)


# 博文列表,按标签
@home.route('/blogs/tags/<int:tid>/')
def tagsblogs(tid):
    # 根据标签id获取标签
    tag = Tags.query.get(tid)
    data = {'tag':tag}

    return render_template('home/blogs/tagslist.html',**data)


# 博文,用户,标签,搜索
@home.route('/blogs/search')
def blogssearch():
    # 接受关键字
    keywords = request.args.get('keywords')
    # 按用户搜索
    users = User.query.filter(User.name.contains(keywords)).all()
    # 博文标题搜索
    blogs = Posts.query.filter(Posts.title.contains(keywords)).all()
    # 组合数据
    data = {'users':users,'blogs':blogs}
    return render_template('/home/blogs/search.html', **data)


# 博文列表 按用户
@home.route('/blogs/user/<int:uid>/')
def userblogs(uid):
    # 获取页码数
    p = int(request.args.get('p',1))
    # 获取博文数据  参数1 当前页码数  参数2 每页显示的数量
    posts = Posts.query.filter_by(uid=uid).paginate(p,5)
    a = list(posts.iter_pages())
    b = len(a)
    # data = {'posts':posts,'a':a, 'b':b}

    # 根据用户id获取当前用户的所有博文列表
    # posts = Posts.query.filter_by(uid=uid).all()
    user = User.query.get(uid)
    data = {'posts': posts, 'user': user,'a':a, 'b':b}
   
    return render_template('home/blogs/userlist.html',**data)


# 评论
@home.route('/comment',methods=["post"])
def comment():
    data={}
    data['context'] = request.values['context']
    data['posts_id'] = request.values['pid']
    data['user_id'] = session['VipUser']['id']

    ob = Comments(**data)
    db.session.add(ob)
    db.session.commit()
    
    res = '<script>alert("评论成功!");location.href="{ok}"</script>'.format(ok=url_for('home.bloginfo',pid=request.values['pid']))
    return res


# 回复
@home.route('/hf',methods=["POST"])
def hf():
    # 获取回复的信息
    data = {}
    data['cid'] = request.values['cid']
    data['context'] = request.values['context']
    data['user_id'] = session['VipUser']['id']
    try:
        data['rid'] = request.values['rid']
    except:
        pass

    # 评论
    r = Comments.query.get(request.values['cid'])
    pid = r.posts_id

    ob = Reply(**data)
    db.session.add(ob)
    db.session.commit()
    res = "<script>alert('回复成功');location.href='{}'</script> ".format(url_for('home.bloginfo',pid=pid))
    return res


# 富文本编辑器配置
@home.route('/ueditconfig/', methods=['GET', 'POST'])
def ueditconfig():
    from app import BASE_DIR
    # 获取请求动作
    action = request.args.get('action')
    result = {}
    # 读取配置文件
    if action == 'config':
    # 初始化时，返回配置文件给客户端
        with open(os.path.join(BASE_DIR,'static', 'ueditor', 'php',
                               'config.json')) as fp:
            try:
                # 删除 `/**/` 之间的注释
                CONFIG = json.loads(re.sub(r'\/\*.*\*\/', '', fp.read()))
            except:
                CONFIG = {}
        result = CONFIG
    # 文件上传
    if action  == 'uploadimage':
        upfile = request.files['upfile']  # 这个表单名称以配置文件为准
        # upfile 为 FileStorage 对象
        # 这里保存文件并返回相应的URL

        Suffix = upfile.filename.split('.').pop()
        filename = str(time.time())+str(random.randint(10000,99999))+'.'+Suffix
        imgurl = '/static/uploads/'+filename
        upfile.save(BASE_DIR+imgurl)

        result = {
            "state": "SUCCESS",
            "url": imgurl,
            "title": filename,
            "original":filename
        }
        print(BASE_DIR)
    return json.dumps(result)


# 登陆
@home.route('/login', methods=['GET', 'POST'])
def login():
    nextpath = request.args.get('next','/')
    # print(nextpath)
    if request.method == 'GET':
        data = {
            'login':url_for('home.login'),
            'register':url_for('home.register')
        }

        return render_template('home/lw-log.html', url=data)
    elif request.method == 'POST':
        email = request.form['email']
        password = User.MD5password(request.values['pwd']) 
        try:
            # 查数据
            ob = User.query.filter_by(email=email).first()
            if password == ob.pwd:
                session['VipUser'] = {
                    'email': email,
                    'id': ob.id, 
                    'phone': ob.phone,
                    'face': ob.face
                    }
                res = '<script>alert("登录成功");location.href="{next}"</script>'.format(next=nextpath)
                return res
            else:
                res = '<script>alert("账号或者密码错误,请重新登录!!");history.back(-1)</script>'
                return res
            
        except:
            res = '<script>alert("账号或者密码错误,请重新登录!!");history.back(-1)</script>'
            return res


# 个人中心
@home.route('/myinfo')
def myinfo():
    uid = session['VipUser']['id']
    ob = User.query.get(uid)
    # 获取页码数
    p = int(request.args.get('p',1))
    # 获取博文数据  参数1 当前页码数  参数2 每页显示的数量
    posts = Posts.query.filter_by(uid=uid).paginate(p,2)
    a = list(posts.iter_pages())
    b = len(a)
    data = {'posts':posts,'a':a, 'b':b, 'ob': ob}
    return render_template('home/myinfo.html', **data)


# 编辑个人信息
@home.route('/editinfo')
def editinfo():
    uid = session['VipUser']['id']
    ob = User.query.get(uid)
    data = {'ob': ob}
    return render_template('home/editinfo.html', **data)


# 执行修改个人信息
@home.route('/update', methods=['POST','GET'])
def update():
    from app import BASE_DIR
    if request.method == 'POST':
        # 获取对象
        uid = session['VipUser']['id']
        ob = User.query.get(uid)
        print(ob.name)
        # 执行修改
        ob.name = request.values['name']
        ob.phone = request.values['phone']
        ob.age = request.values['age']
        ob.sex = request.values['sex']
        ob.info = request.values['info']
        if request.values['pwd']:
            ob.pwd = User.MD5password(request.values['pwd']) 
        try:
            # 检测是否有文件上传
            myfile = request.files['face']
            try:
                os.remove(BASE_DIR + ob.face)
            except:
                pass

            Suffix = myfile.filename.split('.').pop()
            filename = str(time.time())+str(random.randint(10000,99999))+'.'+Suffix

blog-project/app/templates/home/base.html
<!doctype html>
<html>
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>BLOG index with sidebar & slider | Amaze UI Examples</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/static/home/i/favicon.png">
        <meta name="mobile-web-app-capable" content="yes">
        <link rel="icon" sizes="192x192" href="/static/home/i/app-icon72x72@2x.png">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Amaze UI" />
        <link rel="apple-touch-icon-precomposed" href="/static/home/i/app-icon72x72@2x.png">
        <meta name="msapplication-TileImage" content="/static/home/i/app-icon72x72@2x.png">
        <meta name="msapplication-TileColor" content="#0e90d2">
        <link rel="stylesheet" href="/static/home/css/amazeui.min.css">
        <link rel="stylesheet" href="/static/home/css/app.css">
        <script src="/static/home/js/jquery.min.js"></script>
    </head>
    
    <body id="blog">
        <header class="am-g am-g-fixed blog-fixed blog-text-center blog-header">
            <div class="am-u-sm-8 am-u-sm-centered">
                <img width="200" src="/static/home/images/32.jpeg" alt="Amaze UI Logo">
                <h2 class="am-hide-sm-only">欢迎来到你的个人博客世界......</h2>
            </div>
        </header>
       
        <hr>
        <!-- nav start -->
        {% block nav %}
        <nav class="am-g am-g-fixed blog-fixed blog-nav">
            <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button" data-am-collapse="{target: '#blog-collapse'}">
                <span class="am-sr-only">导航切换</span>
                <span class="am-icon-bars"></span>
            </button>
            <div class="am-collapse am-topbar-collapse" id="blog-collapse">
                <ul class="am-nav am-nav-pills am-topbar-nav">
                    <li class="am-active">
                        <a href="{{ url_for('home.home', p=1) }}">首页</a>
                    </li>
                    {% if session['VipUser'] %}
                        <li><a href="{{ url_for('home.myinfo') }}">个人中心</a></li>
                        <li><a href="{{ url_for('home.createblog') }}">发布博文</a></li>
                        <li><a href="lw-index.html">欢迎登陆:{{ session['VipUser']['email'] }}!!</a></li>
                        <li><a href="{{ url_for('home.logout') }}">退出</a></li>
                    {% else %}
                        <li>
                            <a href="{{ url_for('home.login') }}">登录</a>
                        </li>
                        <li>
                            <a href="{{ url_for('home.register') }}">注册</a>
                        </li>
                    {% endif %}
                </ul>
                <form action="{{ url_for('home.blogssearch') }}" method="GET" class="am-topbar-form am-topbar-right am-form-inline" role="search">
                    <div class="am-form-group">
                        <input name="keywords" type="text" class="am-form-field am-input-sm" placeholder="搜索">
                        <button style='border:none;background: #fff;'>
                            <i class="am-icon-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </nav>
        {% endblock %}
        <hr>
        <!-- nav end -->
        {% block banner %}
        
        {% endblock %}

        {% block con %}
        <div class="am-g am-g-fixed blog-fixed">
            {% block conleft %}
            <div class="am-u-md-8 am-u-sm-12">

                <article class="am-g blog-entry-article">
                    <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                        <span><a href="" class="blog-color">article &nbsp;</a></span>
                        <span> @amazeUI &nbsp;</span>
                        <span>2015/10/9</span>
                        <h1><a href="">我本楚狂人，凤歌笑孔丘</a></h1>
                        <p>我们一直在坚持着，不是为了改变这个世界，而是希望不被这个世界所改变。
                        </p>
                        <p><a href="" class="blog-continue">continue reading</a></p>
                    </div>
                </article>

                
                <ul class="am-pagination">
                  <li class="am-pagination-prev"><a href="">&laquo; Prev</a></li>
                  <li class="am-pagination-next"><a href="">Next &raquo;</a></li>
                </ul>
            </div>
            {% endblock %}

            {% block conright %}
            <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
             
                <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
                    <h2 class="blog-title">
                        <span>TAG cloud</span>
                    </h2>
                    <div class="am-u-sm-12 blog-clear-padding">
                        {% for v in 'a'| gettagsall %}
                            <a href="{{ url_for('home.tagsblogs',tid=v.id) }}" class="blog-tag">{{ v.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                
            </div>
            {% endblock %}

        </div>
        {% endblock %}

        <footer class="blog-footer">
            <div class="am-g am-g-fixed blog-fixed am-u-sm-centered blog-footer-padding">
                <div class="am-u-sm-12 am-u-md-4- am-u-lg-4">
                    <h3>模板简介</h3>
                    <p class="am-text-sm">这是一个使用amazeUI做的简单的前端模板。
                        <br>博客/ 资讯类 前端模板
                        <br>支持响应式，多种布局，包括主页、文章页、媒体页、分类页等
                        <br>嗯嗯嗯，不知道说啥了。外面的世界真精彩
                        <br>
                        <br>Amaze UI 使用 MIT 许可证发布，用户可以自由使用、复制、修改、合并、出版发行、散布、再授权及贩售 Amaze UI 及其副本。
                    </p>
                </div>
                <div class="am-u-sm-12 am-u-md-4- am-u-lg-4">
                    <h3>社交账号</h3>
                    <p>
                        <a href="javascript:;">
                            <span class="am-icon-qq am-icon-fw am-primary blog-icon blog-icon"></span>
                        </a>
                        <a href="javascript:;">
                            <span class="am-icon-github am-icon-fw blog-icon blog-icon"></span>
                        </a>
                        <a href="javascript:;">
                            <span class="am-icon-weibo am-icon-fw blog-icon blog-icon"></span>
                        </a>
                        <a href="javascript:;">
                            <span class="am-icon-reddit am-icon-fw blog-icon blog-icon"></span>
                        </a>
                        <a href="javascript:;">
                            <span class="am-icon-weixin am-icon-fw blog-icon blog-icon"></span>
                        </a>
                    </p>
                    <h3>Credits</h3>
                    <p>我们追求卓越，然时间、经验、能力有限。Amaze UI 有很多不足的地方，希望大家包容、不吝赐教，给我们提意见、建议。感谢你们！</p>
                </div>
                <div class="am-u-sm-12 am-u-md-4- am-u-lg-4">
                    <h1>我们站在巨人的肩膀上</h1>
                    <h3>Heroes</h3>
                    <p>
                        <ul>
                            <li>jQuery</li>
                            <li>Zepto.js</li>
                            <li>Seajs</li>
                            <li>LESS</li>
                            <li>...</li>
                        </ul>
                    </p>
                </div>
            </div>
            <div class="blog-text-center">© 2015 AllMobilize, Inc. Licensed under MIT license. Made with love By LWXYFER
            </div>
        </footer>
        <!--[if (gte IE 9)|!(IE)]>
        <!-->
        <!--<![endif]-->
        <!--[if lte IE 8 ]>
            <script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
            <script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
            <script src="/static/home/js/amazeui.ie8polyfill.min.js"></script>
        <![endif]-->
        <script src="/static/home/js/amazeui.min.js"></script>
    </body>

</html>

blog-project/app/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
    <title>首页</title>
    <link rel="stylesheet" type="text/css" href="/static/home/css/index.css">
</head>
<body>
    <h1>首页</h1>
</body>
</html>

blog-project/app/templates/home/myinfo.html
{% extends 'home/base.html' %}

{% block nav %}
    <nav class="am-g am-g-fixed blog-fixed blog-nav">
        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button" data-am-collapse="{target: '#blog-collapse'}">
            <span class="am-sr-only">导航切换</span>
            <span class="am-icon-bars"></span>
        </button>
        <div class="am-collapse am-topbar-collapse" id="blog-collapse">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li class="">
                    <a href="{{ url_for('home.home', p=1) }}">首页</a>
                </li>
                {% if session['VipUser'] %}
                    <li class="am-active"><a href="{{ url_for('home.myinfo') }}">个人中心</a></li>
                    <li><a href="{{ url_for('home.createblog') }}">发布博文</a></li>
                    <li><a href="lw-index.html">欢迎登陆:{{ session['VipUser']['email'] }}!!</a></li>
                    <li><a href="{{ url_for('home.logout') }}">退出</a></li>
                {% else %}
                    <li>
                        <a href="{{ url_for('home.login') }}">登录</a>
                    </li>
                    <li>
                        <a href="{{ url_for('home.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
            <form action="{{ url_for('home.blogssearch') }}" method="GET" class="am-topbar-form am-topbar-right am-form-inline" role="search">
                <div class="am-form-group">
                    <input name="keywords" type="text" class="am-form-field am-input-sm" placeholder="搜索">
                    <button style='border:none;background: #fff;'>
                        <i class="am-icon-search"></i>
                    </button>
                </div>
            </form>
        </div>
    </nav>
{% endblock %}

{% block con %}
<div class="am-g am-g-fixed blog-fixed">
    {% block conleft %}
         <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
            <center>
            <a type="button" class="am-btn am-btn-danger am-radius" href="{{ url_for('home.editinfo') }}">编辑个人信息</a>
            </center>
            <br>
            <br>
            <br>
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>About ME</span></h2>
                <img src='{{ ob.face }}' alt="about me" class="blog-entry-img">
                <p>{{ ob.name }}</p>
                <p>{{ ob.info|d('这个人很懒,P都没留下',true) }}</p>
            </div>
            <div class="blog-sidebar-widget blog-bor">
                <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
                <p>
                    <a href="javascript:;"><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
                    <a href="javascript:;"><span class="am-icon-github am-icon-fw blog-icon"></span></a>
                    <a href="javascript:;"><span class="am-icon-weibo am-icon-fw blog-icon"></span></a>
                    <a href="javascript:;"><span class="am-icon-reddit am-icon-fw blog-icon"></span></a>
                    <a href="javascript:;"><span class="am-icon-weixin am-icon-fw blog-icon"></span></a>
                </p>
            </div>
            <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
                <h2 class="blog-title">
                    <span>TAG cloud</span>
                </h2>
                <div class="am-u-sm-12 blog-clear-padding">
                    {% for v in 'a'| gettagsall %}
                        <a href="{{ url_for('home.tagsblogs',tid=v.id) }}" class="blog-tag">{{ v.name }}</a>
                    {% endfor %}
                </div>
            </div> 
        </div>
    {% endblock %}

    {% block conright %}
       <div class="am-u-md-8 am-u-sm-12">
        {% if ob.posts %}
            
            {% for i in posts.items %}
                <article class="am-g blog-entry-article"> 
                    <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                        <span>作者 &nbsp;</span>
                        <span>
                            <a href="{{ url_for('home.userblogs',uid=ob.id) }}" class="blog-color">@{{ ob.name }} &nbsp;
                            </a>
                        </span> <br>
                        <span>{{ i.addtime }}</span><br>
                        <h1><a href="{{ url_for('home.bloginfo',pid=i.id)}}">{{ i.title }}</a></h1>
                      
                        <!-- <span>{{ i.context|safe }}</span> -->
                    </div>
                </article>
            {% endfor %}
            
            <ul class="am-pagination">
                <li id="first_page" {% if request.args.get('p')|int == 1 %} class="am-disabled" {% endif %}>
                    <a href="javascript:;">首页</a>
                </li>
                <li id="left_btn" {% if request.args.get('p')|int == 1 %} class="am-disabled" {% endif %}>
                    <a href="javascript:;">«</a>
                </li>
               
                {% for v in posts.iter_pages() %}
                <li {% if v == request.args.get('p',1)|int %} class="am-active" {% endif %}>
                    <a class="cli" href="{% if v %} ?p={{ v }} {% else %} javascript:void(0) {% endif %}">{{ v|d('...',true) }}</a>
                </li>
                {% endfor %}
                
                <li id="right_btn" {% if request.args.get('p')|int == a | length %} class="am-disabled" {% endif %}>
                    <a href="javascript:;">»</a>
                </li>
                <li id="last_page" {% if request.args.get('p')|int == a | length %} class="am-disabled" {% endif %}>
                    <a href="javascript:;">尾页</a>
                </li>
            </ul>

        {% else %}
            <div class="am-u-md-8 am-u-sm-12">
                <article class="am-g blog-entry-article"> 
                    <h2>该用户暂时没有文章......</h2>
                </article>  
            </div>
        {% endif %}
        </div>
        <script type="text/javascript">
            $('#first_page').click(function(){
                $(".am-pagination li").eq(2).find('.cli').append("<span></span>");
                $(".am-pagination li").eq(2).find('.cli span').click();
            })


            $('#left_btn').click(function(){
                var num = {{ request.args.get('p',1) }}
                // alert(num)
                $(".am-pagination li").eq(num).find('.cli').append("<span></span>");
                $(".am-pagination li").eq(num).find('.cli span').click();
            })

            $('#right_btn').click(function(){
                var num = {{ request.args.get('p',1) }}
                // alert(num);
                $(".am-pagination li").eq(num+2).find('.cli').append("<span></span>");
                $(".am-pagination li").eq(num+2).find('.cli span').click();
            })

            $('#last_page').click(function(){
                var num = {{ b }}
                $(".am-pagination li").eq(num+1).find('.cli').append("<span></span>");
                $(".am-pagination li").eq(num+1).find('.cli span').click();
            })
        </script>
    {% endblock %}
</div>
{% endblock %}